version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/14/data

volumes:
  gem_cache:
    driver: local
  node_modules:
    driver: local
